#+TITLE: Journal Week 29
#+OPTIONS: toc:2
#+BIBLIOGRAPHY: ../../../references.bib
#+CITE_EXPORT: csl chicago-author-date.csl

* Table of Contents :TOC:noexport:
- [[#referencias][Referencias]]
- [[#2026-07-13][2026-07-13]]
  - [[#1530][[15:30]]]
- [[#2026-07-16][2026-07-16]]
  - [[#1100][[11:00]]]
  - [[#1104][[11:04]]]
  - [[#1558][[15:58]]]

* Referencias
#+PRINT_BIBLIOGRAPHY:

* 2026-07-13

** [15:30]
Instalé en la computadora del Von Karman el software del sensor, usando miniforge en lugar del Anaconda que ya estaba instalado. Esto para poder medir la superficie libre de las pruebas de la semana pasada. La computadora tiene Windows 7 como la de la sala.

* 2026-07-16

** [11:00]
Ya están todas las secciones de la rampa impresas. La más grande pesa solo 89 g. Con los ajugeros más profundos para las tuercas entran bien los tornillos incluso cn el fondo viejo.

También mandamos para probar una sección pequeña de polycarbonato con los mismos features que van a tener las placas más grandes, y salieron bien de la cortadora laáser. Lo único a tener en cuenta es que quema un poco los bordes, pero respeta bien las tolerancias y tamaños de los agujeros y canaletas. Además encaja bien con las partes impresas. A tener en cuenta para el futuro que las líneas de los dibujos se cortan todas, aunque sea punteadas.

Tabién ya pusieron la pizarra en la pared, así que ya colgué los dibujos de todas las piezas y las intrucciones de ensamblaje.

** [11:04]
De momento mandé a imprimir las 5 piezas del ensamblador de los sensores, para poder ir montándolos mientras se fabrican el resto de las piezas. Se supone que deberían tardar las 5 juntas en la cama un total de 2  horas.

** [15:58]
Ya está hecho el ensamblador de sensores. Hubo que lijarlo un poco para que entre bien en el indentador, pero está funcionando. Mañana la idea sería probarlo con los alambres.

Además, la idea es pedir en el taller que vayan rellenando la cama de tornillos mientras hacen otras impresiones. a
