#+TITLE: Journal Week 23
#+OPTIONS: toc:2
#+BIBLIOGRAPHY: ../../../references.bib
#+CITE_EXPORT: csl chicago-author-date.csl

* Table of Contents :TOC:noexport:
- [[#referencias][Referencias]]
- [[#2026-06-01][2026-06-01]]
  - [[#0914][[09:14]]]
  - [[#1020][[10:20]]]
  - [[#1225][[12:25]]]
  - [[#1508][[15:08]]]
  - [[#1513][[15:13]]]
  - [[#1517][[15:17]]]
- [[#2026-06-03][2026-06-03]]
  - [[#0928][[09:28]]]
  - [[#1013][[10:13]]]

* Referencias
#+PRINT_BIBLIOGRAPHY:

* 2026-06-01

** [09:14]
Estuve probando con Claude intentar conectarme a la placa de adquisición de IOTech desde Linux. Le pase =DaqX64.dll= y los drivers =pdaq3k.sys= y =pdaq3kld.sys=.

Aparentemente Linux tiene un dirver generíco para comunicarse con la placa ya que =lsusb= la encuentra como un dispositivo de IOTech. Claude extrajo de los .sys el firmware de la placa y me dió un archivo de Python para comunicarnos pero de momento está en timeout. Recién me quedé sin tokens hasta las 13:30 pero luego jhabría que continuar probando. Durante el intento de carga del firmware interceptamos la comunicación con =tshark= y aparentemente le diálogo inicial tuvo éxito.

** [10:20]
Ya estaría en general terminada la configuración literaria con =config.org=. Solo queda el tema de los ambientes virtuales de Python.

** [12:25]
Ya está funcionando, con un ambiente llamado =~/.env=. Que usa por defecto =pyvenv=.

** [15:08]
Ya tengo configurado también un modo con ~f5~ que interrumpe la ejecución y envía el aarchivo. El modo de output =%xmode=, al printear =KeyboardInterrup= viene por defecto en verboso y printea un montón de cosas, pero se podría cambiar. Además ~f5~ sólo funciona si hay algo que interrumpir, pero supongo que con un if se podría corregir también.

** [15:13]
Queda para hacer de las mediciones del rompimiento de ola:
- Calcular la distribución del número de Iribarren.
- Superponer las partes repetidas y ver qué tan bien definida está la serie temporal.

** [15:17]
Hay una cosa rara con los tildes. Para replicar hay que apagara BloqMáyus e inmediatamenete tocar la tecla del tilde, esto lo que produce es que se ponga diérsis en vez de tilde, por ejemplo en "Cömo" en lugar de "Cómo".

* 2026-06-03

** [09:28]
Estoy descargando Wireshark en Mi Compu con Windows para poder registrar la comunicación de la placa con la computadora, en la búsqueda de poder utilizarla en Linux.
Para esto los pasos son:
1) Abrir Wireshark
2) Elegir USBP cap1, con la placa conectada, y seleccionar la placa.
3) Darle a =start= para iniciar la captura.
4) Desconectar y reconectar la placa, correr el código que le pregunta el nombre o lee un canal analógico.
5) Detenr la captura con ~C-e~ o el cuadrado rojo de arriba a la izquierda (al lado de la aleta de tiburón que permite reiniciar la captura).
6) Guardar la captura como =algo.pcapng=.

** [10:13]
AL conectar hoy la placa en Linux tuve que cambiar la regla udev ya que se modificó el /ATTR{idProduct}=="2c01"/. ESto te das cuenta al correr =lsusb -v= y al ver el número 3 diría =can't open device= si cambió algo. AL corregir esto se soluciona.
